spring.application.name=labflow-backend

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration